### ISSUE TITLE
Automatically keep the local specs up-to-date

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/cs251-toolkit#10]
It would be nice if, instead of having to manually download and update the cs251-specs repository, the toolkit could automatically download and manage the specs for you.

So, instead of having to 

```console
$ git clone https://github.com/StoDevX/cs251-specs data
```

you could just

```console
$ cs251tk --record hw3
Updating specs… done.
Recording hw3 for rives, piersonv, magnusow
```

and have the toolkit itself keep them up to date.

---

I think they'd be stored in `$XDG_DATA_HOME`, with a fallback to `~/.local/share/cs251-specs` or `~/Library/Application Support/cs251-specs`. 

This issue should probably also include a new `--specs $dir` argument, to allow the user to provide a custom location to read spec files from.

**Comment by maxnz** [comment]
Added in #87
