### ISSUE TITLE
Travis build has started failing?

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/cs251-toolkit#103]
https://travis-ci.org/StoDevX/cs251-toolkit/builds/476146856

**Comment by maxnz** [comment]
Looks like it may be a pytest issue: build [#407](https://travis-ci.org/StoDevX/cs251-toolkit/jobs/473353821) used pytest-4.0.2 while build [#408](https://travis-ci.org/StoDevX/cs251-toolkit/jobs/476146669) and on used pytest-4.1.0.

**Comment by maxnz** [comment]
Looks like it was actually a problem with [pytest-cov](https://github.com/OpenAPITools/openapi-generator/issues/1832). Build passes successfully now.

**Comment by maxnz** [comment]
@hawkrives Looks like now it's having trouble logging into Docker: https://travis-ci.org/StoDevX/cs251-toolkit/jobs/476147635#L856

**Comment by rye** [comment]
The `DOCKER_USERNAME` env variable is secret… not sure who set it up, but it's entirely possible that it was me and that my monthly password change policy for public-facing things broke the builds.

I copied my new `DOCKER_PASSWORD` into a var on Travis, if the build suddenly works then we'll know it was my fault. If not, it might have been @hawkrives—either way I'll set `DOCKER_USERNAME` to `kryestofer` and make it not secret so there isn't confusion in the future.

**Comment by rye** [comment]
Changed `DOCKER_USERNAME` to be visible.

Closing again.

**Comment by maxnz** [comment]
Thanks. I'm going to run the deploy to pypi job on there because that version hasn't been uploaded yet.
