### ISSUE TITLE
travis: Pick Docker Tag Better

### ISSUE THREAD

**Issue by rye** [StoDevX/cs251-toolkit#53]
Currently, I disabled our Docker Tag picker script in Travis, because it kept building `HEAD` when I didn't want it to. This was yucky.

I'd much rather have it properly pick a tag based on the environment variables provided by Travis.

**Comment by hawkrives** [comment]
List of Travis-provided env variables: https://docs.travis-ci.com/user/environment-variables/#Default-Environment-Variables

You might want `TRAVIS_TAG` ("If the current build is for a git tag, this variable is set to the tag’s name.") in combination with only building the docker image on tags (you might even be able to hook it into the Deploy section.)

LMK if you want any help.

**Comment by rye** [comment]
***Kinda*** resolved in #55. But, [this](https://travis-ci.org/StoDevX/cs251-toolkit/jobs/206837511#L503-L1163) happened.

**Comment by rye** [comment]
Yikes. Stored my password in plaintext in the logs. Oh well, it's okay. Script is finished and is successfully pushing stuff now.

**Comment by hawkrives** [comment]
If you PM me the build number I can delete the build log. 

Also I think you should have rights to do that yourself – the command to do so is somewhere in the "travis" gem.

**Comment by rye** [comment]
I did do that through the web interface. All is well.

**Comment by hawkrives** [comment]
:+1:
