### ISSUE TITLE
Travis: Use Build Stages™

### ISSUE THREAD

**Issue by rye** [StoDevX/cs251-toolkit#65]
Yay, [Build Stages](https://blog.travis-ci.com/2017-05-11-introducing-build-stages) are a thing.  We should use them.

**Comment by rye** [comment]
Actually, with the way stuff is right now, this doesn't really work for us.  Travis' documentation says that [data doesn't persist between stages and jobs](https://docs.travis-ci.com/user/build-stages#Data-persistence-between-stages-and-jobs) which makes our situation a tad difficult because we build a Docker image when we're testing, and expect to be able to push that when we're done.  I'd rather not rebuild multiple times if I can avoid that.

My plan is to rewrite the deployment script(s) in Bash and use them going forward.  This will make things a bunch cleaner and more maintainable, and will enable us to use Build Stages in a slightly more sane way. (Tests would get carried out outside of the Docker Image, then everything would get packaged up.)  @hawkrives, how does this sound?

**Comment by hawkrives** [comment]
it sounds worth a shot to me!

**Comment by rye** [comment]
Or...maybe we could use Python for the scripts as you had mentioned, too.
