### ISSUE TITLE
Compilation should have a timeout also

### ISSUE THREAD

**Issue by rye** [StoDevX/cs251-toolkit#68]
I had a student submit homework a while ago that recursively included itself, which caused an infinite loop in compilation.  It'd be great if we had a 60-second timeout on compilation.

**Comment by hawkrives** [comment]
Eh, you’re too generous. How about giving it a 10-second timeout?

**Comment by rye** [comment]
Hmm.  Combining multiple concurrent builds together might cause some normal slowdown, especially on larger homeworks.  How about 30 seconds?

**Comment by hawkrives** [comment]
I can't recall any homeworks that took over a few seconds to compile... but we can certainly start at 30 seconds.

I have a thing in here somewhere to set the runtime timeout for individual files; we should eventually add that to allow overriding for specific homeworks, I think.
