### ISSUE TITLE
Toolkit not finding that pypi has an updated version

### ISSUE THREAD

**Issue by maxnz** [StoDevX/cs251-toolkit#79]
I've updated already to 2.3.0 and pypi now shows that 2.3.3 is available, but the toolkit isn't printing a "new version available" message.

**Comment by hawkrives** [comment]
It may take a bit… let's try again in like 15 minutes and see if it shows up?

**Comment by hawkrives** [comment]
Plus I only let the app check every 15 minutes:

https://github.com/StoDevX/cs251-toolkit/blob/aade6ea83162d3339b2ff42ecba23b7d63a316c9/cs251tk/toolkit/config.py#L37-L38

**Comment by maxnz** [comment]
Still nothing...
I ran it every couple minutes for about 20 minutes and then let it sit for another 20 before running again and it still isn't showing anything.

**Comment by maxnz** [comment]
Could it be because of this timeout?
https://github.com/StoDevX/cs251-toolkit/blob/0a6409d433f4a1dedf44537b2bd7e69ff0f73ccc/cs251tk/toolkit/find_update.py#L11

**Comment by maxnz** [comment]
I'm fiddling around with find_update.py and it looks like the toolkit is able to get the page, but can't find the links and thus returns an empty array.

**Comment by maxnz** [comment]
It also looks like it's unable to get the page within the current timeout. The lowest time I've been successful with is 0.5s.

**Comment by maxnz** [comment]
Fixed here #82

**Comment by maxnz** [comment]
It looks like the 15-minute check isn't working properly. It is always checking for a new version and the last update time is listed as September 11, 2018, as far as I can tell. Basically, needs_update_check() is always returning 'true'.
