### ISSUE TITLE
Dockerize The Thing™

### ISSUE THREAD

**Issue by rye** [StoDevX/cs251-toolkit#9]
On Slack, @hawkrives and I briefly discussed converting this project into a Docker project.

In short, this is a fairly trivial sort of process. It just involves (i) writing a Dockerfile, (ii) making sure we don't have any funky system calls that'll break in Docker, and (iii) figuring out our distribution process.

It was mentioned that most graders are using either their own personal macOS or Linux machines, or the lab machines. Docker happily runs in the two former environments, (with the Docker Mac Public Beta working very cleanly for people) and has the potential to resolve *a lot* of woes.

What I propose is this:

* **Make a Dockerfile** to deal with the simplest part of this, which is just packing the code up and putting it in a VM.
  * **Externally load the `spec` and `student.txt` files**.
    * Since these are cloned/manually inputted by the TA/CA, we can expect to include them from the outside using Docker Volumes.
* **Make a helper script** to help you interact with the cs251tk container.
  * That is, rather than force our users to keep typing `docker run -it <image> -- <flags>`, we should just have a script like `./cs251tk <flags>` which simply hands those off and takes care of any Docker-related errors.
* **Clean stuff up** to make it easier to build.
* **Automate our builds** so that TA/CA's don't have to deal with building the thing when they want to use it.
  * *Ideally*, they'd just run `docker pull <our image>` and it would go and pull down the image stack so that all that is needed is about a minute to download everything and get it rolling.
  * *Alternatively*, if we want TA/CA's to use a helper script, we could just make them build it as part of the setup.
    * Since building a Docker container is an automated process, I'm not too concerned about it as long as it's clearly documented in the README.

I'll get on this soon!  I'd love to hear comments or suggestions from people. ✨

**Comment by hawkrives** [comment]
I'm all for as little manual setup as possible! `docker pull $image && cs251tk --stuff` ftw.

I don't know a _ton_ about Docker, though, so I've got a few questions:

1. How would we provide the folders to be used by Docker Volumes? Maybe make a default of `specs=~/cs251/specs` and `students=~/cs251/students`, and then Docker lets the user customize those folders as they wish?
2. We'll also need to include the `students/` folder that contains the student's git repos

And, I guess

3. There have been some people in the past who just used this to orchestrate the pulling of student repos, and didn't use the `--record` feature. They were lab TAs, and ran the stuff only on the lab machines. 
  - For that use case, we could continue to publish on PyPI, and just have them do `pip3 install --user cs251tk`
  - or, um, get RAB to put `dockerd` on the lab machines? Docker seems like a lot of overhead for repo orchestration, though.

**Comment by rye** [comment]
Point-by-point:

The idea will be that, yes, `docker pull $image` will download the actual backend. (this repo) We'll have to figure out what we're doing with the rest of the stuff—eventually we'll have a shell script that, as I say, handles the docker interaction so that people will be able to do `cs251tk --stuff`. (It might be more difficult to begin with, but we'll get there pretty quickly.)

1. In order to have Docker Volumes, we need to figure out how to let users configure this.  Most users will have different preference as to where to put their grading stuff, (some like myself might even want to store on external mounts/NFS shares) so making a file like `~/.cs251tk-config` or something in one of the locations you mentioned in #8 would allow us to `export` environment variables, in its simplest element.
   - Actually *providing* these to the Docker container is as simple as giving it a path on the outside and a path on the inside (i.e. with the flag `-v`, like `-v /path/to/host/dir:/containerdir`.)
   - This also works the same with files, you can mount using the same syntax and Docker is chill.
   - This means that we'll actually be able to put the entire `cs251tk` folder as-is into a folder like `/cs251tk` on the host, and then just mount the host dir to `/cs251tk/data`.
  
I, personally, would recommend against needing to have this configuration, and instead have *one* mount of a directory (e.g. `~/.cs251tk-media/`) containing the `data/`, `students/`, and `students.txt` files into a directory like `/cs251tk/media/` on the container, and then have symlinks in the container to bring all of them out.  This way, the symlinks can just be set up to expect those files to be present, and we'll get a semi-smart error message out if a directory is missing.

**Important Note: Host paths for bind-mounts (what we're talking about) must be absolute paths.** So, like, `docker run -it $image -v /path/to/host:/internal` is good, but `docker run -it $image -v ~/bad/path:/internal` is bad.

2. Adding `students/` should be trivial under the umbrella of the above—we can have as many mounts as we want.

3. If you want to pull, I think it'll have to take place into the `students/` directory, since Docker doesn't let us play with host directories from within containers.

I'd be interested to hear more from people about how they use the toolkit now so I can get an idea of what's up with what and how things need to be piped in.

**Comment by rye** [comment]
`dockerd` doesn't eat too many resources and would make running big jobs in the background on the lab machines a bit easier.  It'd be worth trying, but I'm not an expert on how everything is orchestrated.  It works very well both in production and on a development machine, and the big win is that the same image can be run *both* locally for development and in the wild, with no additional configuration besides installing the image and running.  That's why I'd like to make this happen.

Also, with my idea of having one folder containing all of the files that graders need to look at, we could just make that an environment variable and tell people to set that in their shell config.  That way, the command would just be like

```
$ ls ~/cs251-media
data/ students/ students.txt cs251tk-helper
$ CS251TK_MEDIA_DIR=. ./cs251tk-helper --stuff
# expands CS251TK_MEDIA_DIR to an absolute path, mounts, and runs the thing
```

I'm down for suggestions about names, too.

**Comment by hawkrives** [comment]
> Note that for this entire discussion, I have zero Docker experience beyond a failed attempt to make a dockerfile once. So I have no idea what I'm talking about and am certainly wrong on things. Especially terminology.

That sounds perfectly reasonable to me. I like the environment variable. I'm down for prototyping this, at least; there's no real reason that you and Josh can't use the docker version, while @rachelfrantsen and @petersbob use the PyPI version on the lab machines, I don't think.

I'll leave it to you on-campus peeps to bug RAB / Olaf / Nolan / Bob about installing `dockerd` on the lab machines.

**Comment by rye** [comment]
Since setting Docker up on the link machines is now somewhat in my ballpark, I think I will close this issue as that was the only thing blocking this revision.
