### ISSUE TITLE
Error when checking first submission

### ISSUE THREAD

**Issue by maxnz** [StoDevX/cs251-toolkit#92]
It seems that if the student has turned in something but not anything on the list of files to check in the spec, the code throws this error:

    Traceback (most recent call last):
      File "/home/maxnz/.local/lib/python3.5/site-packages/cs251tk/formatters/markdown.py", line 16, in format_assignment_markdown
        header = format_header(recording, warnings)
      File "/home/maxnz/.local/lib/python3.5/site-packages/cs251tk/formatters/markdown.py", line 42, in format_header
        header = '# {spec} – {student}\n{first_submit}\n'.format_map(recording)
    KeyError: 'first_submit'

Should be fixable with an extra else statement in the last update check code.

**Comment by maxnz** [comment]
It seems that it isn't a problem with the c++ version of CheckDates. I'll take a closer look at it later this week.

**Comment by hawkrives** [comment]
While you're doing that, could we move it from /student/markdownify/ to /common/, please?

**Comment by hawkrives** [comment]
And yeah, I think all you need is an `if not dates: return None` right before the last line.
